### ISSUE TITLE
Upload the solution of the given specific problem.

### ISSUE THREAD

**Issue by Anjalijha12345** [Anjalijha12345/DSA--Problem#1]

**Comment by AnshulGoyal589** [comment]
i would like to work on the issue, kindly assign it to me

**Comment by madm234** [comment]
I can provide clean cpp code for this problem. I would like to code this.

**Comment by ananyapillai72** [comment]
Hey! I can work on this cpp problem.

**Comment by Anjalijha12345** [comment]
@ananyapillai72 yes

**Comment by Anjalijha12345** [comment]
@AnshulGoyal589 Assigned!

**Comment by shivamk23** [comment]
Hlo Anjali,
Can you assign me this problem.
I can write optimize solution for this.

**Comment by hitali-khachane** [comment]
Can u Assign me this.I want to provide solution for this
