### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by thakurdiwakar** [Anjalijha12345/DSA--Problem#38]
Hey @Anjalijha12345 ,i would like to work on the issue, kindly assign it to me

**Comment by belal-akram** [comment]
Hello @Anjalijha12345 
Please Assign this to me.I will complete it.

**Comment by Anjalijha12345** [comment]
@thakurdiwakar @belal-akram Assigned!

**Comment by geekyharsh05** [comment]
Hello @Anjalijha12345,
Can you please assign this to me?

**Comment by Girish345** [comment]
Hello @Anjalijha12345 ,I would like to work on this problem Can you please assign this to me?

**Comment by belal-akram** [comment]
Hello @Anjalijha12345 I have created a pull request "kadane's algo added #44". Could you merge it as this is my first hacktoberfest contribution.

**Comment by mrinalproxy** [comment]
Hello @Anjalijha12345 Can You Assign this issue to me

**Comment by Vikas9kumargupta** [comment]
Hello @Anjalijhan12345 , I would like to work on this problem because i am working in java since last 4 months, Can you assign this task to me

**Comment by Anjalijha12345** [comment]
@Vikas9kumargupta Assigned!

**Comment by Vikas9kumargupta** [comment]
Hey @Anjalijha12345 , Please merge my pull request for kadane's Algorithm.

**Comment by Poonamraut040** [comment]
Hey Anjali can you assign me this ?
