### ISSUE TITLE
Max Subarray Problem

### ISSUE THREAD

**Issue by shrey141102** [Anjalijha12345/DSA--Problem#4]
I will add solution of max subarray problem in Java
please mark it as hacktoberfest

**Comment by Girish345** [comment]
I would like to work on this problem please added me I will give best solution in CPP.

**Comment by ashfaque-mustaque** [comment]
I would like to work on this problem can you assign me??
i can do in multiple languages

**Comment by shrey141102** [comment]
its already done

**Comment by AdityaKumdale** [comment]
Hey I had a doubt, we need to solve issues only labled hactoberfest 2023 or any issue will do for hacktoberfest. What if repos have no issue ,then will we be able to create a issue under hactoberfest 2023. Will it work.

**Comment by shrey141102** [comment]
> Hey I had a doubt, we need to solve issues only labled hactoberfest 2023 or any issue will do for hacktoberfest. What if repos have no issue ,then will we be able to create a issue under hactoberfest 2023. Will it work.

yes you can contribute anyway u want. just ask the person who manages the repo to add labels of hacktoberfest on it

**Comment by Vikas9kumargupta** [comment]
I would like to work on this problem please added me I will give best solution in Java.

**Comment by hitali-khachane** [comment]
I want to add solution for this Can U please Assign this to me So that I can provide solution containing less Timecomplexity.

**Comment by Anjali2312-Thombare** [comment]
hey @shrey141102  I will solve this with all possible approaches .can you please assign me this issue?

**Comment by bhavesh-2004** [comment]
hey @shrey141102 I would like to solve this task by best optimal approach so can you please assign me this work i am very interested  to solve this issue..

**Comment by shrey141102** [comment]
Hey this is not my repository. Please ask the owner > hey @shrey141102 I would like to solve this task by best optimal approach so can you please assign me this work i am very interested  to solve this issue..
