### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by Shorya7** [Anjalijha12345/DSA--Problem#52]
I want to contribute the code of SOE in C++ under hactoberfest 2023.

**Comment by Girish345** [comment]
Hey @Anjalijha12345 ,I would like to work on the issue, can you please assign it to me.

**Comment by Vikas9kumargupta** [comment]
Hey @Anjalijha12345 ,I want to contribute the code of SOE in Java under hactoberfest 2023.

**Comment by Anjalijha12345** [comment]
@Girish345 @Shorya7 @Vikas9kumargupta you can work on this repo https://github.com/diwakar1593/CPP-Problems
