### ISSUE TITLE
Knapsack Problem

### ISSUE THREAD

**Issue by avanish729** [Anjalijha12345/DSA--Problem#53]
I want to comtribute Knapsack Problem in C++ for hactoberfest 2023 .

**Comment by himughanakash** [comment]
I want to give knapsack problem's code in cpp

**Comment by Yash493** [comment]
Hey Can u Assign this issue to me, I have good knowledge in Data Structure and Algorithms and I can write code in Java ,C++ and c language

**Comment by Anjalijha12345** [comment]
@Yash493 @himughanakash @avanish729 you can work on this repo https://github.com/diwakar1593/CPP-Problems

**Comment by Poonamraut040** [comment]
can you assign me this , I will write the best code with less time complexity in cpp
