### ISSUE TITLE
Bounded Traversal of Matrix

### ISSUE THREAD

**Issue by okaditya84** [Anjalijha12345/DSA--Problem#9]
I am willing to contribute my Python and C++ code for bounded traversal of matrix. 
This code will be well structured and commented for beginners to understand.
Kindly assign me this issue.

**Comment by bhaveshgarg2000** [comment]
@Anjalijha12345 Please assign me this issue. I'm willing to solve this issue

**Comment by SayaliMarathe-13** [comment]
Hello,
I'm relatively new to open source and GitHub. I'm eager to learn and improve my skills, and I believe working on this issue will be a valuable experience for me. could you please assign it to me

**Comment by iamrishabhjoshi** [comment]
Please assign this issue to me. I will like to contribute in this repository.

**Comment by ashfaque-mustaque** [comment]
Hello i wanna to contribute in your repo....
can you assign me?
